#!/bin/sh

set -e

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"

echo "
Copying ez-haskell-nix template to the current directory..."

cp -a "$SCRIPT_DIR/template/." ./

echo "Success!

TODO:

  1) Run './nix-shell.sh'

  2) Init new project with 'stack new --bare my-best-app scotty-hspec-wai --force'

  3) Run 'vi stack.yaml' and adjust some settings if needed:
       
       resolver: lts-14.21
       system-ghc: true

  4) Run 'stack test' and follow stack instructions if something is not working

  5) Run 'vi .' and enjoy comfortable Haskell development :)
"
