configure: &configure
  docker:
  - image: nixos/nix:2.3
  resource_class: xlarge

release: &release
  run:
    name: Create release
    command: ./.circleci/release.sh
    no_output_timeout: 60m

filters: &filters
  filters:
    branches:
      only:
        - master

version: 2
jobs:
  release:
    <<: *configure
    steps:
    - checkout
    - setup_remote_docker
    - *release
  release-publish:
    <<: *configure
    steps:
    - checkout
    - setup_remote_docker
    - *release
    - run:
        name: Load docker image
        command: docker load -i result
    - run:
        name: Login docker
        command: echo -e "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    - run:
        name: Push docker image
        command: docker push "$(docker images heathmont/TODO_DEFINE_APP --format "{{.Repository}}:{{.Tag}}")"

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          <<: *filters
          cron: "0 5 * * *"  # 05:00 UTC
    jobs:
      - release:
          <<: *filters
          context: global
  push:
    jobs:
      - release-publish:
          <<: *filters
          context: global

